[debug] [2024-01-30T05:52:23.672Z] ----------------------------------------------------------------------
[debug] [2024-01-30T05:52:23.675Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\L E N O V O\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js login
[debug] [2024-01-30T05:52:23.676Z] CLI Version:   13.1.0
[debug] [2024-01-30T05:52:23.677Z] Platform:      win32
[debug] [2024-01-30T05:52:23.677Z] Node Version:  v18.16.1
[debug] [2024-01-30T05:52:23.679Z] Time:          Tue Jan 30 2024 11:22:23 GMT+0530 (India Standard Time)
[debug] [2024-01-30T05:52:23.679Z] ----------------------------------------------------------------------
[debug] 
[debug] [2024-01-30T05:52:23.684Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[info] Already logged in as durgasirishamungi@gmail.com
[debug] [2024-01-30T05:52:33.806Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\L E N O V O\AppData\Roaming\npm\node_modules\firebase-tools\lib\utils.js:258:49)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2024-01-30T05:57:23.427Z] ----------------------------------------------------------------------
[debug] [2024-01-30T05:57:23.430Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\L E N O V O\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js login
[debug] [2024-01-30T05:57:23.431Z] CLI Version:   13.1.0
[debug] [2024-01-30T05:57:23.432Z] Platform:      win32
[debug] [2024-01-30T05:57:23.432Z] Node Version:  v18.16.1
[debug] [2024-01-30T05:57:23.434Z] Time:          Tue Jan 30 2024 11:27:23 GMT+0530 (India Standard Time)
[debug] [2024-01-30T05:57:23.434Z] ----------------------------------------------------------------------
[debug] 
[debug] [2024-01-30T05:57:23.439Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[info] Already logged in as durgasirishamungi@gmail.com
[debug] [2024-01-30T05:57:33.564Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\L E N O V O\AppData\Roaming\npm\node_modules\firebase-tools\lib\utils.js:258:49)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2024-01-30T05:59:15.534Z] ----------------------------------------------------------------------
[debug] [2024-01-30T05:59:15.537Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\L E N O V O\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js login
[debug] [2024-01-30T05:59:15.538Z] CLI Version:   13.1.0
[debug] [2024-01-30T05:59:15.538Z] Platform:      win32
[debug] [2024-01-30T05:59:15.539Z] Node Version:  v18.16.1
[debug] [2024-01-30T05:59:15.540Z] Time:          Tue Jan 30 2024 11:29:15 GMT+0530 (India Standard Time)
[debug] [2024-01-30T05:59:15.541Z] ----------------------------------------------------------------------
[debug] 
[debug] [2024-01-30T05:59:15.546Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[info] Already logged in as durgasirishamungi@gmail.com
[debug] [2024-01-30T05:59:37.115Z] ----------------------------------------------------------------------
[debug] [2024-01-30T05:59:37.118Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\L E N O V O\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js init
[debug] [2024-01-30T05:59:37.119Z] CLI Version:   13.1.0
[debug] [2024-01-30T05:59:37.120Z] Platform:      win32
[debug] [2024-01-30T05:59:37.120Z] Node Version:  v18.16.1
[debug] [2024-01-30T05:59:37.122Z] Time:          Tue Jan 30 2024 11:29:37 GMT+0530 (India Standard Time)
[debug] [2024-01-30T05:59:37.122Z] ----------------------------------------------------------------------
[debug] 
[debug] [2024-01-30T05:59:37.127Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[debug] [2024-01-30T05:59:37.214Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2024-01-30T05:59:37.214Z] > authorizing via signed-in user (durgasirishamungi@gmail.com)
[info] 
     ######## #### ########  ######## ########     ###     ######  ########
     ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##
     ######    ##  ########  ######   ########  #########  ######  ######
     ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
     ##       #### ##     ## ######## ########  ##     ##  ######  ########

You're about to initialize a Firebase project in this directory:

  C:\Users\L E N O V O\OneDrive\Desktop\junglebook\TEAM-6

[debug] [2024-01-30T05:59:58.327Z] *** [apiv2] error from fetch(https://firebase-public.firebaseio.com/cli.json, {"headers":{},"method":"GET"}): FetchError: request to https://firebase-public.firebaseio.com/cli.json failed, reason: connect ETIMEDOUT 2600:1901:0:4d00:::443
[warn] !  Unable to fetch the CLI MOTD and remote config. This is not a fatal error, but may indicate an issue with your network connection. 
[debug] [2024-01-30T05:59:58.329Z] Failed to fetch MOTD FirebaseError: Failed to make request to https://firebase-public.firebaseio.com/cli.json
[debug] [2024-01-30T06:01:08.937Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\L E N O V O\AppData\Roaming\npm\node_modules\firebase-tools\lib\utils.js:258:49)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2024-01-30T06:02:20.311Z] ----------------------------------------------------------------------
[debug] [2024-01-30T06:02:20.314Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\L E N O V O\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js init
[debug] [2024-01-30T06:02:20.315Z] CLI Version:   13.1.0
[debug] [2024-01-30T06:02:20.315Z] Platform:      win32
[debug] [2024-01-30T06:02:20.316Z] Node Version:  v18.16.1
[debug] [2024-01-30T06:02:20.317Z] Time:          Tue Jan 30 2024 11:32:20 GMT+0530 (India Standard Time)
[debug] [2024-01-30T06:02:20.317Z] ----------------------------------------------------------------------
[debug] 
[debug] [2024-01-30T06:02:20.323Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[debug] [2024-01-30T06:02:20.409Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2024-01-30T06:02:20.410Z] > authorizing via signed-in user (durgasirishamungi@gmail.com)
[info] 
     ######## #### ########  ######## ########     ###     ######  ########
     ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##
     ######    ##  ########  ######   ########  #########  ######  ######
     ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
     ##       #### ##     ## ######## ########  ##     ##  ######  ########

You're about to initialize a Firebase project in this directory:

  C:\Users\L E N O V O\OneDrive\Desktop\junglebook\TEAM-6

[debug] [2024-01-30T06:02:32.506Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\L E N O V O\AppData\Roaming\npm\node_modules\firebase-tools\lib\utils.js:258:49)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2024-01-30T06:03:35.631Z] ----------------------------------------------------------------------
[debug] [2024-01-30T06:03:35.634Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\L E N O V O\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js deploy
[debug] [2024-01-30T06:03:35.635Z] CLI Version:   13.1.0
[debug] [2024-01-30T06:03:35.635Z] Platform:      win32
[debug] [2024-01-30T06:03:35.636Z] Node Version:  v18.16.1
[debug] [2024-01-30T06:03:35.637Z] Time:          Tue Jan 30 2024 11:33:35 GMT+0530 (India Standard Time)
[debug] [2024-01-30T06:03:35.638Z] ----------------------------------------------------------------------
[debug] 
[debug] [2024-01-30T06:03:35.643Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[debug] [2024-01-30T06:03:40.751Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\L E N O V O\AppData\Roaming\npm\node_modules\firebase-tools\lib\utils.js:258:49)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[error] 
[error] Error: An unexpected error has occurred.
